// "use client"
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const resp = await fetch('http://localhost:9000/topics',{cache:'no-store'})
  const topics = await resp.json()
  return (
    <html lang="en">
      <body>
      <h1><Link href="/">Hello nextjs!</Link></h1>
      <ol>
        {
          topics.map((topic)=>{
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>
                  {topic.title}
                </Link>
              </li>
            )
          })
        }
      </ol>
        {children}
        <ol>
        <li><a href="/create">Create</a></li>
        <li>Update</li>
        <button>Delete</button>
      </ol>
        </body>
    </html>
  );
}
