import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <h1><Link href="/">Hello nextjs!</Link></h1>
      <ol>
        <li>
          <Link href="/read/1">
          HTML
          </Link>
          </li>
        <li>
          <Link href="/read/2">
          CSS
          </Link>
          </li>
      </ol>
        {children}
        <ol>
        <li><a href="/create">Create</a></li>
        <li>Update</li>
        <button>Delete</button>
      </ol>
        </body>
    </html>
  );
}
